WebSite/WebTool/Controllers/Account/AccountBaseController.cs
namespace WebTool
{
    using System;
    using System.Web;
    using System.Web.Mvc;
    using WebToolCulture;
    using WebToolService;

    public abstract class AccountBaseController : BaseController
    {
        public virtual void AddModelError(LogOnModel userModel)
        {
            if (!string.IsNullOrEmpty(userModel?.ErrorMessage))
            {
                this.ModelState.AddModelError(string.Empty, userModel.ErrorMessage);
            }
        }

        public void DoLogOff()
        {
            if (this.Request.Cookies[ConstParameter.WebToolUserName] != null)
            {
                this.Request.Cookies[ConstParameter.WebToolUserName].Expires = DateTime.Now.AddDays(-1);
                this.Response.Cookies.Add(this.Request.Cookies[ConstParameter.WebToolUserName]);
            }
        }

        public ActionResult DoLogOn(LogOnModel logOnModel)
        {
            bool isAllowed = false;
            if (this.ModelState.IsValid)
            {
                isAllowed = this.UserService.IsLogOnAllowed(logOnModel);
                this.AddModelError(logOnModel);
            }

            if (isAllowed)
            {
                this.SetLogOnCookie(logOnModel);

                return this.RedirectToHomePage();
            }
            else
            {
                return this.View(this.MainCshtmlName, logOnModel);
            }
        }

        public ActionResult RedirectToHomePage()
        {
            return this.RedirectToAction("Index", "Home");
        }

        public void SetLogOnCookie(LogOnModel logOnModel)
        {
            string encryptedUsername = this.AESHelper.EncryptStringToBytes(logOnModel.UserName);
            HttpCookie cookie = new HttpCookie(ConstParameter.WebToolUserName, encryptedUsername);
            this.SetLoginCookieExpires(cookie, logOnModel.RememberMe);
            this.Response.Cookies.Add(cookie);
        }

        private void SetLoginCookieExpires(HttpCookie cookie, bool isRemeber)
        {
            if (isRemeber)
            {
                cookie.Expires = DateTime.Now.AddMonths(1);
            }
            else
            {
                cookie.Expires = DateTime.Now.AddDays(1);
            }
        }
    }
}

WebSite/WebTool/Controllers/Account/AccountController.cs
namespace WebTool
{
    using System.Web.Mvc;
    using WebToolService;

    public class AccountController : AccountBaseController
    {
        public override string MainCshtmlName => "~/Views/Account/LogOn/LogOn.cshtml";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Justification = "Justification ")]
        [HttpGet]
        public ActionResult Login()
        {
            this.DoLogOff();
            return this.View(this.MainCshtmlName, new LogOnModel());
        }

        ////[CaptchaVerify("Captchaisnotvalid", typeof(UIResource))]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Justification = "Justification ")]
        [HttpPost]
        public ActionResult Login(LogOnModel logOnModel)
        {
            return this.DoLogOn(logOnModel);
        }
    }
}

WebSite/WebTool/Controllers/Account/RegisterController.cs
namespace WebTool
{
    using System.Web.Mvc;
    using WebToolService;

    public class RegisterController : AccountBaseController
    {
        public override string MainCshtmlName => "~/Views/Account/Register/Register.cshtml";

        public ActionResult Index()
        {
            return this.View(this.MainCshtmlName, new RegisterModel());
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Justification = "Justification ")]
        [HttpPost]
        public ActionResult Index(RegisterModel registerModel)
        {
            ActionResult result;

            bool success = false;

            if (ModelState.IsValid)
            {
                success = UserService.Insert(registerModel);
                this.AddModelError(registerModel);
            }

            if (success)
            {
                this.DoLogOn(registerModel);
                result = this.RedirectToHomePage();
            }
            else
            {
                result = this.View(this.MainCshtmlName, registerModel);
            }

            return result;
        }
    }
}

WebSite/WebTool/Controllers/Home/HomeController.cs
namespace WebTool
{
    using System.Web.Mvc;

    [LogOnCheck]
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return this.View("~/Views/Home/Home.cshtml");
        }
    }
}

WebSite/WebTool/Controllers/Home/IndexHeadController.cs
namespace WebTool
{
    using System.Web.Mvc;

    [LogOnCheck]
    public class IndexHeadController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return this.PartialView("~/Views/Head/Head.cshtml", this.CurrentUserModel);
        }
    }
}

WebSite/WebTool/Controllers/Home/LanguageController.cs
namespace WebTool
{
    using System.Web.Mvc;
    using WebToolCulture;

    public class LanguageController : BaseController
    {
        public ActionResult Index()
        {
           string language = this.Request?.Cookies?[ConstParameter.WebToolLanguage]?.Value;

           return this.PartialView("~/Views/Head/Language/LanguageBar.cshtml", this.LanguageService.GetLanguageModel(language));
        }
    }
}

WebSite/WebTool/Controllers/Tool/ToolController.cs
namespace WebTool
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Microsoft.Practices.Unity;
    using Utilities;
    using WebToolCulture.Resource;
    using WebToolService;

    [LogOnCheck]
    public class ToolController : TableBaseController
    {
        private string fileName = string.Empty;

        public CmdHelper CMDHelper { get; } = new CmdHelper();

        public string FileName
        {
            get
            {
                this.fileName = this.fileName.Length == 0 ? this.Server.MapPath("~/bin/Service/WOL/WolCmd.exe") : this.fileName;
                return this.fileName;
            }

            set
            {
                this.fileName = value;
            }
        }

        public override IList<string> PropertyList => new List<string>()
        {
            nameof(WolModel.WOLID),
            nameof(WolModel.WolName),
            nameof(WolModel.HostName),
            nameof(WolModel.MacAddress),
            nameof(WolModel.SubnetMask),
            nameof(WolModel.Port),
            nameof(WolModel.Protocol)
        };

        public WolModel WOLModel { get; set; }

        public IWolService WOLService { get; set; }

        [InjectionMethod]
        public void Init(IWolService wolService)
        {
            this.WOLService = wolService;
        }

        ////[HttpPost, ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult WakeUp()
        {
            this.WOLModel = this.WOLService.GetWolById(this.CurrentUserModel.UserId).List.FirstOrDefault();

            if (this.WOLModel != null)
            {
                this.WOLModel.FileName = this.FileName;
                this.WOLModel.Wake();
            }

            return this.Json(UIResource.Done);
        }

        [HttpGet]
        public ActionResult WOL()
        {
            return this.View("~/Views/WOL/WOL.cshtml");
        }

        [JsonTable]
        public ActionResult WOLTable(JQueryTable model)
        {
            var listWrapper = this.WOLService.GetWolById(this.CurrentUserModel.UserId, model);

            return this.JsonTable(model, listWrapper);
        }
    }
}

WebSite/WebTool/Views/Head/Footer.cshtml
<!-- BEGIN FOOTER -->
<div class="footer">
    @DateTime.Now.Year &copy; @System.Environment.MachineName
    <div class="span pull-right">
        <span class="go-top"><i class="icon-angle-up"></i></span>
    </div>
</div>
<!-- END FOOTER -->

WebSite/WebTool/Views/Head/Head.cshtml
@model WebToolService.UserModel

<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="navbar-inner" ng-controller="headController as head">
        <div class="container-fluid">
            <!-- BEGIN LOGO -->
            <a class="brand" ng-click="head.brand_Click()">
                <span class="sprite-home sprite-home-logo"></span>
            </a>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                <span class="sprite-home sprite-home-menu-toggler"></span>
            </a>

            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <ul class="nav pull-right">
                @Html.Action("Index", "Language")
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <li class="dropdown user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="dropdown-toggle-image sprite-home sprite-home-avatar1_small"></span>
                        <span class="username">@(Model?.UserName)</span> <i class="icon-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a ng-click="head.myProfile_Click()"><i class="icon-user"></i>@UIResource.MyProfile</a></li>
                        <li class="divider"></li>
                        <li><a ng-click="head.logOut_Click()"><i class="icon-key"></i>@UIResource.LogOut</a></li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
            </ul>
            <!-- END TOP NAVIGATION MENU -->
        </div>
    </div>
    <!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->

WebSite/WebTool/Views/Head/Language/LanguageBar.cshtml
@model WebToolService.LanguageModel
<li ng-controller="languageBarController as languageBar" class="dropdown language" style="line-height: 16px;">
    <a id="change-language-dropdown" href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <span class="current-language sprite-home sprite-home-@Model.CurrentLanguage.PictureName"></span>
        <span name="current-language-text" class="username current-language-text">
            @Model.CurrentLanguage.Name
        </span>
        <i class="fa fa-angle-down"></i>
    </a>
    @foreach (var language in Model.ListLanguage)
    {
        <ul class="dropdown-menu">
            <li>
                <a id="language-icon" ng-click="languageBar.changeLanguage('@language.Code');">
                    <span class="language-list sprite-home sprite-home-@language.PictureName"></span>
                    <span class="language-list-name">@language.Name</span>   
                </a>
            </li>
        </ul>

    }

</li>

WebSite/WebTool/Views/Home/Home.cshtml
@using System.Web.Optimization
@{ Layout = "~/Views/Shared/_indexLayout.cshtml"; }

@{
    HeaderCaption HeaderCaption = new HeaderCaption()
    {
        Header1 = UIResource.Dashboard,
        Header2 = UIResource.StatisticsAndMore,
        Navigation1 = UIResource.Home,
        Navigation1Click = "Home_Click();",
        Navigation2 = UIResource.Dashboard,
        Navigation2Click = "Dashboard_Click();",
    };
}
<div id="dashboard" ng-controller="homeController as home">
    @Html.Partial("~/Views/Shared/HeaderPanel/HeaderPanel.cshtml", HeaderCaption)
    <div class="row-fluid">
        @Html.Partial("~/Views/Home/Panel/WakeUpPanel.cshtml")
    </div>
</div>
@section scripts
{
    @Scripts.Render("~/Content/Home")
}

WebSite/WebTool/Views/Home/Panel/WakeUpPanel.cshtml
<div ng-controller="M.wakeUpPanelController as wakeUpPanel" class="span3 responsive" data-tablet="span6  fix-offset" data-desktop="span3">
    <div class="dashboard-stat blue">
        <div class="visual">
            <i class="icon-globe"></i>
        </div>
        <a id="home-wake-up" class="more" ng-click="wakeUpPanel.wakeUp_Click()">
            @UIResource.WakeUp <i class="m-icon-swapright m-icon-white"></i>
        </a>
    </div>
    <div id="alertWakeUpSuccess" ng-cloak ng-show="wakeUpPanel.isShowAlertWakeUpSuccess" class="alert alert-success">
        <button class="close" ng-click="wakeUpPanel.hideSuccessMessage()"></button>
        <strong>@UIResource.Success</strong>
    </div>
</div>

WebSite/WebTool/Views/Shared/HeaderPanel/HeaderPanel.cshtml
@model HeaderCaption
<div ng-controller="M.headerPanelController as headerPanel" class="row-fluid">
    <div class="span12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            @Model.Header1 <small>@Model.Header2</small>
        </h3>
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i><a ng-click="headerPanel.navigation1Click()">@Model.Navigation1</a>
                <span class="icon-angle-right"></span>
            </li>
            <li>
                <a ng-click="headerPanel.navigation2Click()">@Model.Navigation2</a>
            </li>
            <li class="pull-right no-text-shadow">
                <div id="dashboard-report-range" class="dashboard-date-range tooltips no-tooltip-on-touch-device responsive"
                     data-tablet="" data-desktop="tooltips" data-placement="top" data-original-title="Change dashboard date range">
                    <i class="icon-calendar"></i><span></span><i class="icon-angle-down"></i>
                </div>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>

WebSite/WebTool/Views/Shared/JS/AntiForgeryToken.cshtml
@Html.AntiForgeryToken()

WebSite/WebTool/Views/Shared/JS/BackendResource.cshtml
@using WebTool
@{
    var resourceString = Html.Raw(((BaseController)ViewContext.Controller).ResourceJson);

    string controller = Request?.RequestContext?.RouteData?.Values?["controller"]?.ToString();
    string action = Request?.RequestContext?.RouteData?.Values?["action"]?.ToString();
}
<script>
window.UIResource = @(resourceString);
window.controller = '@controller';
window.action = '@action';
</script>

WebSite/WebTool/Views/Shared/JS/PageEnd.cshtml
<script>
(function () {
    (function SendPageSpeedTimings(controller, action) {

        var pageEndTime = new Date().getTime();
        var timeSpent = pageEndTime - pageStartTime;
        ga('send', 'timing', controller, action, timeSpent);
    })(window.controller, window.action);

}());
</script>

WebSite/WebTool/Views/Shared/JS/PageStart.cshtml
<script>
(function () {
    window.pageStartTime = new Date().getTime();

    var GA_AccountID = "UA-44048426-1";
    var MyDomain = "cloudapp.net";


    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    (function AddGA() {
        ga('create', GA_AccountID, MyDomain);
        ga('send', 'pageview');
    })();


    window._gaq = window._gaq || [];
    _gaq.push(['_setAccount', GA_AccountID]);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

})();
</script>

WebSite/WebTool/Views/Shared/_ValidationSummary.cshtml
@model ModelStateDictionary

@if (!Model.IsValid)
{
    <div name='alert-error' class='alert alert-error'>
        <div class='text'>
            <p>
                @foreach (var modelError in Model.SelectMany(keyValuePair => keyValuePair.Value.Errors))
                {
                    @modelError.ErrorMessage
                }
            </p>
        </div>
    </div>
}

WebSite/WebTool/Views/Shared/_bootstrapLayout.cshtml
<script>
    window.baseUrl = '@Url.Content("~")';
</script>

WebSite/WebTool/Views/Shared/_indexLayout.cshtml
@{ Layout = "~/Views/Shared/_rootLayout.cshtml"; }
<div class="fixed-top" ng-controller="M.mainController as main">
    <!-- BEGIN HEADER -->
    @Html.Action("Index", "IndexHead")
    @Html.Partial("~/Views/Shared/_bootstrapLayout.cshtml")
    <!-- END HEADER -->

    <div id="Loading" class="dataTables_processing" style="visibility: hidden;"><i class="fa fa-coffee"></i>&nbsp;Please wait...</div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container row-fluid">
        <!-- BEGIN SIDEBAR -->
        @Html.Partial("~/Views/Sidebar/Sidebar.cshtml")
        <!-- END SIDEBAR -->
        <!-- BEGIN PAGE -->
        <div class="page-content">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- END PAGE -->
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    @RenderSection("scripts", false)
    @Html.Partial("~/Views/Head/Footer.cshtml")
    <!-- END FOOTER -->
</div>

WebSite/WebTool/Views/Shared/_rootLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @Html.Partial("~/Views/Shared/JS/PageStart.cshtml")

    @Html.Partial("~/Views/Shared/JS/BackendResource.cshtml")

    @*    @Html.Partial("~/Views/Shared/JS/AntiForgeryToken.cshtml")*@
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" />
    @Styles.Render("~/Content/AllCSS")
</head>
<body ng-app="mainApp">
    @RenderBody()
</body>

@Html.Partial("~/Views/Shared/JS/PageEnd.cshtml")
</html>

WebSite/WebTool/Views/Sidebar/Sidebar.cshtml
<div ng-controller="M.sidebarController as sidebar" class="page-sidebar nav-collapse collapse">
    <!-- BEGIN SIDEBAR MENU -->
    <ul class="page-sidebar-menu">
        <li id="Dashboard" ng-class="{active: sidebar.activePanel.dashboard}">
            <a ng-click="sidebar.LeftPanel_Dashboard_Click()">
                <i class="icon-home"></i>@UIResource.Dashboard
                <span class="selected"></span>
                <span class="arrow"></span>
            </a>
        </li>
    </ul>
    <ul class="page-sidebar-menu">
        <li id="WOL" ng-class="{active: sidebar.activePanel.wol}">
            <a ng-click="sidebar.LeftPanel_WOL_Click()">
                <i class="icon-th-list"></i>@UIResource.WOL
                <span class="selected"></span>
                <span class="arrow"></span>
            </a>
        </li>
    </ul>
    <!-- END SIDEBAR MENU -->
</div>

WebSite/WebTool/Views/WOL/WOL.cshtml
@using System.Web.Optimization
@{ Layout = "~/Views/Shared/_indexLayout.cshtml"; }

@{
    HeaderCaption HeaderCaption = new HeaderCaption()
    {
        Header1 = UIResource.WOL,
        Header2 = UIResource.WakeOnLan,
        Navigation1 = UIResource.WOL,
        Navigation1Click = "WOL_Click();",
        Navigation2 = UIResource.WakeOnLan,
        Navigation2Click = "WOL_Click();",
    };
}
@Html.Partial("~/Views/Shared/HeaderPanel/HeaderPanel.cshtml", HeaderCaption)



<div ng-controller="wolController as wol" class="row-fluid">
    <div class="responsive" data-tablet="span12 fix-offset">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4><i class="icon-reorder"></i>@UIResource.WOLList</h4>
                <div class="tools">
                    <a class="collapse"></a>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="WOLTable">
                    <thead>
                        <tr>
                            <th>WOLID</th>
                            <th>@UIResource.WOLName</th>
                            <th>@UIResource.HostName</th>
                            <th>@UIResource.MACAddress</th>
                            <th>@UIResource.SubnetMask</th>
                            <th>@UIResource.Port</th>
                            <th>@UIResource.Protocol</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
@section scripts{
    @Scripts.Render("~/Content/Wol")
}